name: Build Docker Image

on:
  push:
    branches:
      - develop
      - main

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: actorforth/bitcoin-cash-node

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: |
          export TAG_BITCOINCASHNODE=$(git describe --always --tags --dirty --abbrev=7 | sed 's/^.*\(.\{7\}\)/\1/')
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG_BITCOINCASHNODE -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest ./

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(git describe --always --tags --dirty --abbrev=7 | sed 's/^.*\(.\{7\}\)/\1/')
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
